# Generated by Django 3.2.7 on 2021-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classletter', models.CharField(max_length=255, verbose_name='Буква класса')),
                ('numberofclass', models.IntegerField(default=0, unique=True, verbose_name='Номер класса')),
                ('superviser', models.CharField(max_length=255, verbose_name='Классный руководитель')),
            ],
        ),
    ]
