# Generated by Django 3.2.7 on 2021-09-11 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('clas', models.CharField(max_length=255, verbose_name='Касс')),
                ('number', models.IntegerField(verbose_name='Номер родителей')),
                ('location', models.CharField(max_length=255, verbose_name='Место проживания')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes', verbose_name='Уроки')),
            ],
        ),
    ]
