# Generated by Django 3.2.7 on 2021-09-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото завуча')),
                ('number', models.IntegerField(default=0, verbose_name='Номер')),
            ],
            options={
                'verbose_name_plural': 'Завучи',
            },
        ),
    ]
